kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-pv
  namespace: preprod
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /pv-data
    type: DirectoryOrCreate